steps:
  - label: triggering
    env:
      DEBUG: true
      SOMESTUFF: "thestuff"
    plugins:
      chronotc/monorepo-diff#c236df78ce66bf1d7ad1721e5f07627172d39097:
        diff: "./examples/diff. ${BUILDKITE_COMMIT}"
        watch:
          - path: "bar/"
            config:
              trigger: "staging-bar"
              build:
                env:
                  - FOO=BAR
                  - SOMESTUFF

